name: Run Build
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm test
  license: 
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build
        run: npm ci && npm run build

      - name: Update OSS_LICENSES text file
        run: npm run update-license

      - name: Commit and push the file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update OSS_LICENSES.txt file'
          push_options: '--force'
  